[package]
name = "ovsc-hal"
description = "The OpenVirtualSoundcard Core Audio server plug-in (AudioServerPlugIn driver)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "ovsc-hal-selftest"
path = "src/bin/ovsc-hal-selftest.rs"

[dependencies]
ovsc-shm.workspace = true
ovsc-ipc.workspace = true
arc-swap.workspace = true
libc.workspace = true

[lints]
workspace = true
