[package]
name = "ovsc"
description = "OpenVirtualSoundcard virtual soundcard daemon and command-line tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "ovsc"
path = "src/main.rs"

[dependencies]
ovsc-proto.workspace = true
ovsc-clock.workspace = true
ovsc-core.workspace = true
ovsc-soundcard.workspace = true
ovsc-shm.workspace = true
ovsc-ipc.workspace = true
ovsc-hal-server.workspace = true
ovsc-control.workspace = true
anyhow.workspace = true
libc.workspace = true
clap.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["io-util"] }
toml.workspace = true
toml_edit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
